name: expense_tracker
description: A simple expense tracker application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.11.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # ✅ SQLite
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.19.0
  csv: ^5.1.1
  file_picker: ^8.0.0


flutter:
  uses-material-design: true
